
2022-03-14 13:32:46,489:__main__:
Filename: ABC invoice 0R7642.png. Error occured in Active Learning table.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 568, in trigger_table
    All_files=os.listdir(Table_text_path)
FileNotFoundError: [Errno 2] No such file or directory: './../output_data/b7688ede/standard_invoice/ABC invoice 0R7642.png/outputs/Table_txt'

2022-03-14 13:32:46,489:__main__:
Filename: ABC invoice 0R7642.png. Error occured in Active Learning table.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 568, in trigger_table
    All_files=os.listdir(Table_text_path)
FileNotFoundError: [Errno 2] No such file or directory: './../output_data/b7688ede/standard_invoice/ABC invoice 0R7642.png/outputs/Table_txt'

2022-03-14 13:32:46,490:__main__:
Filename: Baltic 2022-01-14.jpg. Error occured in Active Learning table.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 568, in trigger_table
    All_files=os.listdir(Table_text_path)
FileNotFoundError: [Errno 2] No such file or directory: './../output_data/b7688ede/standard_invoice/Baltic 2022-01-14.jpg/outputs/Table_txt'

2022-03-14 13:32:46,490:__main__:
Filename: Baltic 2022-01-14.jpg. Error occured in Active Learning table.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 568, in trigger_table
    All_files=os.listdir(Table_text_path)
FileNotFoundError: [Errno 2] No such file or directory: './../output_data/b7688ede/standard_invoice/Baltic 2022-01-14.jpg/outputs/Table_txt'
